channel_select(). this function rocks ! I adapted the sample.c file. the select_loop function is bloated and fails to demonstrate how libssh is simple to handle...
it looks to run at first try.


git-svn-id: svn+ssh://svn.berlios.de/svnroot/repos/libssh/trunk@39 7dcaeef0-15fb-0310-b436-a5af3365683c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3852,6 +3852,20 @@ fi
 done
 
 
+#Warn user when no openssl available
+#FIXME ! how to make it work with gcrypt ?
+if test x"$ac_cv_header_openssl_aes_h" != x"yes" ||
+x"$ac_cv_header_openssl_blowfish_h" != x"yes"; then
+        echo "Can't find valid openssl files e.g openssl/aes.h"
+        echo "Please install Openssl-devel"
+        exit
+fi
+
+if ! test x"$ac_cv_header_zlib_h" = x"yes"; then
+        echo "Can't find zlib.h"
+        echo "Compression support won't be compiled in"
+fi
+
 # Checks for typedefs, structures, and compiler characteristics.
 echo "$as_me:$LINENO: checking for an ANSI C-conforming const" >&5
 echo $ECHO_N "checking for an ANSI C-conforming const... $ECHO_C" >&6
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -54,6 +54,21 @@ sys/time.h termios.h unistd.h openssl/aes.h openssl/blowfish.h \
 openssl/des.h zlib.h sys/poll.h stdint.h pty.h pam/pam_appl.h \
 security/pam_appl.h gcrypt.h])
 
+#Warn user when no openssl available
+#FIXME ! how to make it work with gcrypt ?
+#I can't make it work. help would be appreciated
+#if test x"$ac_cv_header_openssl_aes_h" != x"yes" ||
+#x"$ac_cv_header_openssl_blowfish_h" != x"yes"; then
+#        echo "Can't find valid openssl files [e.g openssl/aes.h]"
+#        echo "Please install Openssl-devel"
+#        exit
+#fi
+
+#if ! test x"$ac_cv_header_zlib_h" != x"yes"; then
+#        echo "Can't find zlib.h"
+#        echo "Compression support won't be compiled in"
+#fi
+
 # Checks for typedefs, structures, and compiler characteristics.
 AC_C_CONST
 AC_HEADER_TIME
